/*
To let the signal reset asynchronously and recover synchronously
*/

module as_s(
    input nRST_rc,          //Reset signal without jitter
    input switch,           //Clock switch signal, generated by clock_switch
    input clk_out,          //the selected clk signal
    output reg reset_n      //final reset signal
);

reg reg1,reg2;
wire nmid;
assign nmid = nRST_rc&switch;
always@(posedge clk_out, negedge nmid)begin
    if(!nmid)begin
        reg1<=0;
        reg2<=0;
    end else begin
        reg1<=1;
        reg2<=reg1;
    end
end
always @(*)begin
    reset_n=reg2;
end

endmodule